[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "afb144826ee1ad684362d54f57c13fbb9610a465"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "f5bc8f5233fa9e874b9176edbd943b6cc880c15294aa863eaa884ec8b341eaa9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.aarch64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "dbb6282d474b6dcd724b83cb19784a4d0847687b"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "ad1b04f2a3fedbd6a0e9f380294e16bb90800d6a9a750559d349233d7f461b6d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.aarch64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "f12ca9e01d698b4588a778b6f4e120fcdd8211a4"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "1fdf881ee0c42e9e996b63685d48d1b6099f1b834e1814f97c86291a9051c8eb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.aarch64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "32dc4f0f7d27ad21e274017c470f59425b8d8ab3"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "78362f2ef3000d21a2fe746475febc700f515c71f3eb52a653850288a5b157af"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b711f078169f8878a7a4a7186df4f648678ae6f9"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "bec28e6687db25832dc97fd9a3b9b4dbdd27134449c51da14d0fe1b7a74a806b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58f6b5822334d4b56b2708053067683e69c218fc"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "0729c1ed08937f5e9b9abb273c019cc7f3bd8d7c70f7f648947c2eb35543b83e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9d09ff0e57a77bc9636a800141182bd213ee6d9"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "73e078651f9bcdc1f755adcb99cf2d612ca4f5d04ff145f423d5ffaf0174d372"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "983cca0351b594cff4e5c8a4135576eb1974dc5a"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "cf597d643ac4918b6d15d15962e1cda2aa1526dfa85d7ea9a7d50b5d55733b38"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "bfb9cae21a5d7ffcb9aa31289cde2fbaddd7a3a9"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "54fa35f64e1a21f39c396cc9b7fe401025c0ae151eb1ea09a06b4c42b1b953ea"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.i686-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "0d215bb76659ce7d1cb5eebbc59ad73076428113"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "ddb7c99b4b717ffa170f161e11df7cae0abfc96905b9a9b8b99e431677e4d374"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.i686-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "powerpc64le"
git-tree-sha1 = "bd9a2474ad78014dd035e1ec5e07078a734a6e65"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "377151ce2150afad534d9fe354852cb42655e1ec51d54e3691e40e1c8b81bccf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "riscv64"
git-tree-sha1 = "37a214344b533f7142b6ec76d0b21952b9ebd1c7"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "fea692e111fd7d5bd3aeecce0b2e5d2a1c6be9e48ade776cd7b662d93f018ab4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.riscv64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "82cecf06382d1fb3e060cdcfa5c8a253957751c1"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "05ddc3a8629cec79b13489f8baf4aa434908635cb3839b07ce9244511e61af7e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.x86_64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "280344a115917aea98fde740436b1fe466328b02"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "cd7912174df03faca2fbe983ee4c41c52190e8ac9b0c2943593a042e72584af9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.x86_64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "0cf96354176a7e46502452ee032d7e012b984f90"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "a42ead1d7bd164807112f8d8caf07ce3d1bef018b1a260a691e85b2636cace83"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.x86_64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "3905b91390b133387625c618ed92a7e435c9d43d"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "e1bb981c2328367179807fb46179479cc5fd52923c9c391a088c191600c5d442"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "e15a99d9ad6f6c16cff7add1f06a6707826f170d"
os = "windows"

    [[aws_c_http_jq.download]]
    sha256 = "b1cb25973a78b119bb5e561d594085d3b66faa43885b83bc2a66bcda5293c770"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.8+0/aws_c_http_jq.v0.10.8.x86_64-w64-mingw32.tar.gz"
